### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by kyleericson** [kyewei/osxhidtouch#1]
How do you install this?

**Comment by kyewei** [comment]
If you happen to have the exact same hardware as i do, namely touchscreen with VID 0x04f3 and PID 0x0086 (check system information for that), you can just download the binary in the binary folder and run it from anywhere. Otherwise, just change the appropriate numbers and compile with xcode.

**Comment by kyleericson** [comment]
I have a Viewsonic TD2420 Series

**Comment by kyewei** [comment]
Seeing as that is an optical touchscreen, this definitely won't work with it.
